[config]
schemaVersion = "0.0.1"

[package]
namespace = "Pixelnaut"
name = "ExtractAnywhere"
versionNumber = "1.0.3"
description = "Allows resource extraction to function without the need for natural resources. Also allows changing the maximum size of resource extractors' areas."
websiteUrl = "https://github.com/T3nak/cities-skylines-2-extract-anywhere"
containsNsfwContent = false

[package.dependencies]
# BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods" ]
