name: cities-skylines-2-extract-anywhere

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bepinex-version: [5, 6]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Checkout libcs2
        uses: actions/checkout@v3
        with:
          repository: T3nak/cities-skylines-2-extract-anywhere-deps
          token: ${{ secrets.GH_PAT }}
          path: libcs2/
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build (BepInEx ${{ matrix.bepinex-version }})
        run: make package-unix BEPINEX_VERSION=${{ matrix.bepinex-version }}
      - name: Upload Artifact (BepInEx ${{ matrix.bepinex-version }})
        uses: actions/upload-artifact@v3
        with:
          name: built-code-${{ matrix.bepinex-version }}
          path: dist/*.dll
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: built-code-5
          path: dist/
      - name: Debug
        run: ls && ls dist/
      - name: Download tcli
        run: dotnet tool install -g tcli
      - name: Publish with tcli
        run: tcli publish --token=${{ secrets.TS_TOKEN }}
